import yaml
from yaml.loader import SafeLoader
from flask import Flask, render_template, request
from authenticator import Authenticate

app = Flask(__name__)

with open('../config.yaml') as file:
    config = yaml.load(file, Loader=SafeLoader)

authenticator = Authenticate(
    config['credentials'],
    config['cookie']['name'],
    config['cookie']['key'],
    config['cookie']['expiry_days'],
    config['preauthorized']
)

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        if authenticator.authenticate(username, password):
            return render_template('dashboard.html', username=username)
        else:
            return render_template('login.html', error=True)
    else:
        name, authentication_status, username = authenticator.login('Login', 'main')
        return render_template('login.html', name=name, authentication_status=authentication_status)

if __name__ == '__main__':
    app.run()
